"""initial schema

Revision ID: 68067a5c1d6b
Revises: 
Create Date: 2026-03-26 17:17:42.827210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '68067a5c1d6b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contractors',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=False),
    sa.Column('service_area_zips', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('specialties', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('license_number', sa.String(length=100), nullable=False),
    sa.Column('license_status', sa.String(length=50), nullable=False),
    sa.Column('license_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('insurance_verified', sa.Boolean(), nullable=False),
    sa.Column('years_in_business', sa.Integer(), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('score_breakdown', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('data_sources_count', sa.Integer(), nullable=False),
    sa.Column('last_data_refresh', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contractors_slug'), 'contractors', ['slug'], unique=True)
    op.create_index(op.f('ix_contractors_zip_code'), 'contractors', ['zip_code'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('payment_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_project_id'), 'payments', ['project_id'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_table('project_contractors',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('contractor_id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('matched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('project_id', 'contractor_id')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('project_type', sa.String(length=50), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=False),
    sa.Column('scope', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('preferences', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('cost_estimate_low', sa.Float(), nullable=True),
    sa.Column('cost_estimate_high', sa.Float(), nullable=True),
    sa.Column('cost_confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'intake'"), nullable=False),
    sa.Column('tier', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_session_id'), 'projects', ['session_id'], unique=False)
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('contractor_reviews',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('contractor_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=False),
    sa.Column('review_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contractor_reviews_contractor_id'), 'contractor_reviews', ['contractor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contractor_reviews_contractor_id'), table_name='contractor_reviews')
    op.drop_table('contractor_reviews')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_session_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('project_contractors')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_project_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_contractors_zip_code'), table_name='contractors')
    op.drop_index(op.f('ix_contractors_slug'), table_name='contractors')
    op.drop_table('contractors')
    # ### end Alembic commands ###
