"""
Seed script for the AI Home Renovation Platform.

Populates the database with 20 realistic contractors across
bathroom, kitchen, windows, and roofing specialties.

Usage:
    docker compose exec backend python -m app.seed
    # or via Makefile:
    make seed
"""

import os
import sys
import uuid
from datetime import datetime, timedelta, timezone

from sqlalchemy import create_engine, text
from sqlalchemy.orm import Session

# ---------------------------------------------------------------------------
# Database URL – prefer the synchronous variant; fall back to converting async
# ---------------------------------------------------------------------------
DATABASE_URL_SYNC = os.getenv("DATABASE_URL_SYNC")
if not DATABASE_URL_SYNC:
    async_url = os.getenv("DATABASE_URL", "")
    DATABASE_URL_SYNC = async_url.replace("postgresql+asyncpg://", "postgresql://")

engine = create_engine(DATABASE_URL_SYNC, echo=False)

# ---------------------------------------------------------------------------
# Import model *after* engine is created so Base is already defined elsewhere
# ---------------------------------------------------------------------------
from app.domain.contractors.models import Contractor  # noqa: E402

# ---------------------------------------------------------------------------
# Contractor seed data
# ---------------------------------------------------------------------------
CONTRACTORS: list[dict] = [
    # ── Bathroom (5) ──────────────────────────────────────────────────────
    {
        "business_name": "Pacific Coast Renovations",
        "slug": "pacific-coast-renovations",
        "phone": "(310) 555-0101",
        "email": "info@pacificcoastreno.com",
        "website": "https://pacificcoastreno.com",
        "zip_code": "90210",
        "service_area_zips": ["90210", "90211", "90212"],
        "specialties": ["bathroom", "full-remodel", "tile-work"],
        "license_number": "CA-LIC-884512",
        "license_status": "active",
        "license_expiry": datetime(2027, 6, 15, tzinfo=timezone.utc),
        "insurance_verified": True,
        "years_in_business": 18,
        "composite_score": 94.2,
        "score_breakdown": {
            "review_score": 4.8,
            "license_score": 100,
            "insurance_score": 100,
            "experience_score": 90,
            "responsiveness_score": 88,
        },
        "data_sources_count": 5,
        "last_data_refresh": datetime.now(timezone.utc) - timedelta(days=3),
        "is_active": True,
    },
    {
        "business_name": "Beverly Hills Bath & Tile",
        "slug": "beverly-hills-bath-tile",
        "phone": "(310) 555-0102",
        "email": "contact@bhbathtile.com",
        "website": "https://bhbathtile.com",
        "zip_code": "90211",
        "service_area_zips": ["90210", "90211", "90212", "90213"],
        "specialties": ["bathroom", "shower-installation", "luxury-bath"],
        "license_number": "CA-LIC-773201",
        "license_status": "active",
        "license_expiry": datetime(2027, 3, 1, tzinfo=timezone.utc),
        "insurance_verified": True,
        "years_in_business": 12,
        "composite_score": 89.5,
        "score_breakdown": {
            "review_score": 4.6,
            "license_score": 100,
            "insurance_score": 100,
            "experience_score": 78,
            "responsiveness_score": 82,
        },
        "data_sources_count": 4,
        "last_data_refresh": datetime.now(timezone.utc) - timedelta(days=5),
        "is_active": True,
    },
    {
        "business_name": "AquaLux Bathrooms",
        "slug": "aqualux-bathrooms",
        "phone": "(212) 555-0201",
        "email": "hello@aqualuxbath.com",
        "website": "https://aqualuxbath.com",
        "zip_code": "10001",
        "service_area_zips": ["10001", "10002", "10003"],
        "specialties": ["bathroom", "accessible-bath", "plumbing"],
        "license_number": "NY-LIC-220145",
        "license_status": "active",
        "license_expiry": datetime(2026, 12, 31, tzinfo=timezone.utc),
        "insurance_verified": True,
        "years_in_business": 9,
        "composite_score": 82.0,
        "score_breakdown": {
            "review_score": 4.3,
            "license_score": 100,
            "insurance_score": 100,
            "experience_score": 68,
            "responsiveness_score": 75,
        },
        "data_sources_count": 3,
        "last_data_refresh": datetime.now(timezone.utc) - timedelta(days=7),
        "is_active": True,
    },
    {
        "business_name": "Windy City Bath Co",
        "slug": "windy-city-bath-co",
        "phone": "(312) 555-0301",
        "email": "info@windycitybath.com",
        "website": "https://windycitybath.com",
        "zip_code": "60601",
        "service_area_zips": ["60601", "60602"],
        "specialties": ["bathroom", "tub-to-shower", "water-damage-repair"],
        "license_number": "IL-LIC-556789",
        "license_status": "active",
        "license_expiry": datetime(2027, 8, 20, tzinfo=timezone.utc),
        "insurance_verified": True,
        "years_in_business": 7,
        "composite_score": 78.3,
        "score_breakdown": {
            "review_score": 4.1,
            "license_score": 100,
            "insurance_score": 100,
            "experience_score": 58,
            "responsiveness_score": 70,
        },
        "data_sources_count": 3,
        "last_data_refresh": datetime.now(timezone.utc) - timedelta(days=10),
        "is_active": True,
    },
    {
        "business_name": "FreshStart Bathroom Remodeling",
        "slug": "freshstart-bathroom-remodeling",
        "phone": "(212) 555-0202",
        "email": "team@freshstartbath.com",
        "website": "https://freshstartbath.com",
        "zip_code": "10002",
        "service_area_zips": ["10001", "10002", "10003", "10004"],
        "specialties": ["bathroom", "vanity-installation", "flooring"],
        "license_number": "NY-LIC-330298",
        "license_status": "active",
        "license_expiry": datetime(2026, 9, 15, tzinfo=timezone.utc),
        "insurance_verified": False,
        "years_in_business": 5,
        "composite_score": 71.6,
        "score_breakdown": {
            "review_score": 4.0,
            "license_score": 100,
            "insurance_score": 0,
            "experience_score": 48,
            "responsiveness_score": 65,
        },
        "data_sources_count": 2,
        "last_data_refresh": datetime.now(timezone.utc) - timedelta(days=14),
        "is_active": True,
    },
    # ── Kitchen (5) ───────────────────────────────────────────────────────
    {
        "business_name": "Elite Kitchen Design",
        "slug": "elite-kitchen-design",
        "phone": "(310) 555-0103",
        "email": "info@elitekitchendesign.com",
        "website": "https://elitekitchendesign.com",
        "zip_code": "90212",
        "service_area_zips": ["90210", "90211", "90212"],
        "specialties": ["kitchen", "cabinet-installation", "countertops"],
        "license_number": "CA-LIC-901234",
        "license_status": "active",
        "license_expiry": datetime(2027, 11, 30, tzinfo=timezone.utc),
        "insurance_verified": True,
        "years_in_business": 22,
        "composite_score": 96.0,
        "score_breakdown": {
            "review_score": 4.9,
            "license_score": 100,
            "insurance_score": 100,
            "experience_score": 95,
            "responsiveness_score": 92,
        },
        "data_sources_count": 6,
        "last_data_refresh": datetime.now(timezone.utc) - timedelta(days=1),
        "is_active": True,
    },
    {
        "business_name": "Manhattan Kitchen Works",
        "slug": "manhattan-kitchen-works",
        "phone": "(212) 555-0203",
        "email": "contact@manhattankw.com",
        "website": "https://manhattankw.com",
        "zip_code": "10001",
        "service_area_zips": ["10001", "10002", "10003"],
        "specialties": ["kitchen", "full-remodel", "smart-kitchen"],
        "license_number": "NY-LIC-441567",
        "license_status": "active",
        "license_expiry": datetime(2027, 4, 10, tzinfo=timezone.utc),
        "insurance_verified": True,
        "years_in_business": 15,
        "composite_score": 91.1,
        "score_breakdown": {
            "review_score": 4.7,
            "license_score": 100,
            "insurance_score": 100,
            "experience_score": 85,
            "responsiveness_score": 86,
        },
        "data_sources_count": 5,
        "last_data_refresh": datetime.now(timezone.utc) - timedelta(days=4),
        "is_active": True,
    },
    {
        "business_name": "ChicagoCraft Kitchens",
        "slug": "chicagocraft-kitchens",
        "phone": "(312) 555-0302",
        "email": "hello@chicagocraftkitchens.com",
        "website": "https://chicagocraftkitchens.com",
        "zip_code": "60602",
        "service_area_zips": ["60601", "60602", "60603"],
        "specialties": ["kitchen", "backsplash", "island-build"],
        "license_number": "IL-LIC-667890",
        "license_status": "active",
        "license_expiry": datetime(2026, 10, 5, tzinfo=timezone.utc),
        "insurance_verified": True,
        "years_in_business": 10,
        "composite_score": 84.7,
        "score_breakdown": {
            "review_score": 4.4,
            "license_score": 100,
            "insurance_score": 100,
            "experience_score": 72,
            "responsiveness_score": 78,
        },
        "data_sources_count": 4,
        "last_data_refresh": datetime.now(timezone.utc) - timedelta(days=6),
        "is_active": True,
    },
    {
        "business_name": "BudgetPro Kitchen Renovations",
        "slug": "budgetpro-kitchen-renovations",
        "phone": "(310) 555-0104",
        "email": "sales@budgetprokitchen.com",
        "website": "https://budgetprokitchen.com",
        "zip_code": "90210",
        "service_area_zips": ["90210", "90211"],
        "specialties": ["kitchen", "budget-remodel", "painting"],
        "license_number": "CA-LIC-445678",
        "license_status": "active",
        "license_expiry": datetime(2026, 7, 22, tzinfo=timezone.utc),
        "insurance_verified": True,
        "years_in_business": 4,
        "composite_score": 68.9,
        "score_breakdown": {
            "review_score": 3.9,
            "license_score": 100,
            "insurance_score": 100,
            "experience_score": 40,
            "responsiveness_score": 60,
        },
        "data_sources_count": 2,
        "last_data_refresh": datetime.now(timezone.utc) - timedelta(days=12),
        "is_active": True,
    },
    {
        "business_name": "TriBeCa Kitchen Studio",
        "slug": "tribeca-kitchen-studio",
        "phone": "(212) 555-0204",
        "email": "info@tribekakitchen.com",
        "website": "https://tribekakitchen.com",
        "zip_code": "10003",
        "service_area_zips": ["10001", "10002", "10003", "10004", "10005"],
        "specialties": ["kitchen", "high-end-appliances", "custom-cabinetry"],
        "license_number": "NY-LIC-559012",
        "license_status": "active",
        "license_expiry": datetime(2027, 1, 18, tzinfo=timezone.utc),
        "insurance_verified": True,
        "years_in_business": 20,
        "composite_score": 92.8,
        "score_breakdown": {
            "review_score": 4.8,
            "license_score": 100,
            "insurance_score": 100,
            "experience_score": 92,
            "responsiveness_score": 85,
        },
        "data_sources_count": 5,
        "last_data_refresh": datetime.now(timezone.utc) - timedelta(days=2),
        "is_active": True,
    },
    # ── Windows (5) ───────────────────────────────────────────────────────
    {
        "business_name": "ClearView Windows",
        "slug": "clearview-windows",
        "phone": "(310) 555-0105",
        "email": "info@clearviewwindows.com",
        "website": "https://clearviewwindows.com",
        "zip_code": "90211",
        "service_area_zips": ["90210", "90211", "90212"],
        "specialties": ["windows", "energy-efficient", "sliding-doors"],
        "license_number": "CA-LIC-678901",
        "license_status": "active",
        "license_expiry": datetime(2027, 5, 10, tzinfo=timezone.utc),
        "insurance_verified": True,
        "years_in_business": 14,
        "composite_score": 88.4,
        "score_breakdown": {
            "review_score": 4.5,
            "license_score": 100,
            "insurance_score": 100,
            "experience_score": 82,
            "responsiveness_score": 80,
        },
        "data_sources_count": 4,
        "last_data_refresh": datetime.now(timezone.utc) - timedelta(days=4),
        "is_active": True,
    },
    {
        "business_name": "NY Window Experts",
        "slug": "ny-window-experts",
        "phone": "(212) 555-0205",
        "email": "service@nywindowexperts.com",
        "website": "https://nywindowexperts.com",
        "zip_code": "10002",
        "service_area_zips": ["10001", "10002", "10003"],
        "specialties": ["windows", "double-pane", "noise-reduction"],
        "license_number": "NY-LIC-112345",
        "license_status": "active",
        "license_expiry": datetime(2027, 2, 28, tzinfo=timezone.utc),
        "insurance_verified": True,
        "years_in_business": 11,
        "composite_score": 85.2,
        "score_breakdown": {
            "review_score": 4.4,
            "license_score": 100,
            "insurance_score": 100,
            "experience_score": 76,
            "responsiveness_score": 77,
        },
        "data_sources_count": 4,
        "last_data_refresh": datetime.now(timezone.utc) - timedelta(days=6),
        "is_active": True,
    },
    {
        "business_name": "Lakeshore Glass & Window",
        "slug": "lakeshore-glass-window",
        "phone": "(312) 555-0303",
        "email": "info@lakeshoreglass.com",
        "website": "https://lakeshoreglass.com",
        "zip_code": "60601",
        "service_area_zips": ["60601", "60602"],
        "specialties": ["windows", "storefront-glass", "skylights"],
        "license_number": "IL-LIC-778901",
        "license_status": "active",
        "license_expiry": datetime(2026, 11, 15, tzinfo=timezone.utc),
        "insurance_verified": True,
        "years_in_business": 25,
        "composite_score": 90.6,
        "score_breakdown": {
            "review_score": 4.6,
            "license_score": 100,
            "insurance_score": 100,
            "experience_score": 96,
            "responsiveness_score": 83,
        },
        "data_sources_count": 5,
        "last_data_refresh": datetime.now(timezone.utc) - timedelta(days=3),
        "is_active": True,
    },
    {
        "business_name": "GreenPane Window Solutions",
        "slug": "greenpane-window-solutions",
        "phone": "(310) 555-0106",
        "email": "hello@greenpane.com",
        "website": "https://greenpane.com",
        "zip_code": "90210",
        "service_area_zips": ["90210", "90211", "90212", "90213"],
        "specialties": ["windows", "vinyl-windows", "eco-friendly"],
        "license_number": "CA-LIC-334567",
        "license_status": "expired",
        "license_expiry": datetime(2025, 12, 31, tzinfo=timezone.utc),
        "insurance_verified": False,
        "years_in_business": 3,
        "composite_score": 65.0,
        "score_breakdown": {
            "review_score": 3.8,
            "license_score": 40,
            "insurance_score": 0,
            "experience_score": 30,
            "responsiveness_score": 55,
        },
        "data_sources_count": 2,
        "last_data_refresh": datetime.now(timezone.utc) - timedelta(days=20),
        "is_active": True,
    },
    {
        "business_name": "TriState Window Installers",
        "slug": "tristate-window-installers",
        "phone": "(212) 555-0206",
        "email": "team@tristatewindow.com",
        "website": "https://tristatewindow.com",
        "zip_code": "10003",
        "service_area_zips": ["10001", "10002", "10003", "10004"],
        "specialties": ["windows", "bay-windows", "historic-restoration"],
        "license_number": "NY-LIC-667234",
        "license_status": "active",
        "license_expiry": datetime(2027, 7, 1, tzinfo=timezone.utc),
        "insurance_verified": True,
        "years_in_business": 17,
        "composite_score": 87.1,
        "score_breakdown": {
            "review_score": 4.5,
            "license_score": 100,
            "insurance_score": 100,
            "experience_score": 86,
            "responsiveness_score": 79,
        },
        "data_sources_count": 4,
        "last_data_refresh": datetime.now(timezone.utc) - timedelta(days=5),
        "is_active": True,
    },
    # ── Roofing (5) ───────────────────────────────────────────────────────
    {
        "business_name": "Summit Roofing Co",
        "slug": "summit-roofing-co",
        "phone": "(312) 555-0304",
        "email": "info@summitroofing.com",
        "website": "https://summitroofing.com",
        "zip_code": "60602",
        "service_area_zips": ["60601", "60602", "60603"],
        "specialties": ["roofing", "shingle-replacement", "storm-damage"],
        "license_number": "IL-LIC-889012",
        "license_status": "active",
        "license_expiry": datetime(2027, 9, 30, tzinfo=timezone.utc),
        "insurance_verified": True,
        "years_in_business": 21,
        "composite_score": 93.5,
        "score_breakdown": {
            "review_score": 4.8,
            "license_score": 100,
            "insurance_score": 100,
            "experience_score": 93,
            "responsiveness_score": 90,
        },
        "data_sources_count": 6,
        "last_data_refresh": datetime.now(timezone.utc) - timedelta(days=2),
        "is_active": True,
    },
    {
        "business_name": "SoCal Roof Masters",
        "slug": "socal-roof-masters",
        "phone": "(310) 555-0107",
        "email": "contact@socalroofmasters.com",
        "website": "https://socalroofmasters.com",
        "zip_code": "90212",
        "service_area_zips": ["90210", "90211", "90212"],
        "specialties": ["roofing", "tile-roof", "flat-roof"],
        "license_number": "CA-LIC-556234",
        "license_status": "active",
        "license_expiry": datetime(2027, 4, 15, tzinfo=timezone.utc),
        "insurance_verified": True,
        "years_in_business": 16,
        "composite_score": 86.9,
        "score_breakdown": {
            "review_score": 4.4,
            "license_score": 100,
            "insurance_score": 100,
            "experience_score": 84,
            "responsiveness_score": 76,
        },
        "data_sources_count": 4,
        "last_data_refresh": datetime.now(timezone.utc) - timedelta(days=8),
        "is_active": True,
    },
    {
        "business_name": "Empire State Roofing",
        "slug": "empire-state-roofing",
        "phone": "(212) 555-0207",
        "email": "info@empirestateroof.com",
        "website": "https://empirestateroof.com",
        "zip_code": "10001",
        "service_area_zips": ["10001", "10002", "10003"],
        "specialties": ["roofing", "commercial-roof", "leak-repair"],
        "license_number": "NY-LIC-778345",
        "license_status": "active",
        "license_expiry": datetime(2026, 8, 20, tzinfo=timezone.utc),
        "insurance_verified": True,
        "years_in_business": 13,
        "composite_score": 83.4,
        "score_breakdown": {
            "review_score": 4.3,
            "license_score": 100,
            "insurance_score": 100,
            "experience_score": 80,
            "responsiveness_score": 72,
        },
        "data_sources_count": 3,
        "last_data_refresh": datetime.now(timezone.utc) - timedelta(days=9),
        "is_active": True,
    },
    {
        "business_name": "Reliable Roof & Gutter",
        "slug": "reliable-roof-gutter",
        "phone": "(312) 555-0305",
        "email": "service@reliableroof.com",
        "website": "https://reliableroof.com",
        "zip_code": "60601",
        "service_area_zips": ["60601", "60602"],
        "specialties": ["roofing", "gutter-installation", "insulation"],
        "license_number": "IL-LIC-990123",
        "license_status": "active",
        "license_expiry": datetime(2027, 1, 10, tzinfo=timezone.utc),
        "insurance_verified": True,
        "years_in_business": 8,
        "composite_score": 76.8,
        "score_breakdown": {
            "review_score": 4.0,
            "license_score": 100,
            "insurance_score": 100,
            "experience_score": 60,
            "responsiveness_score": 68,
        },
        "data_sources_count": 3,
        "last_data_refresh": datetime.now(timezone.utc) - timedelta(days=11),
        "is_active": True,
    },
    {
        "business_name": "TopDeck Roofing Solutions",
        "slug": "topdeck-roofing-solutions",
        "phone": "(212) 555-0208",
        "email": "hello@topdeckroofing.com",
        "website": None,
        "zip_code": "10003",
        "service_area_zips": ["10002", "10003"],
        "specialties": ["roofing", "metal-roof", "solar-ready"],
        "license_number": "NY-LIC-885567",
        "license_status": "active",
        "license_expiry": datetime(2027, 10, 25, tzinfo=timezone.utc),
        "insurance_verified": False,
        "years_in_business": 6,
        "composite_score": 73.2,
        "score_breakdown": {
            "review_score": 4.1,
            "license_score": 100,
            "insurance_score": 0,
            "experience_score": 52,
            "responsiveness_score": 63,
        },
        "data_sources_count": 2,
        "last_data_refresh": datetime.now(timezone.utc) - timedelta(days=15),
        "is_active": True,
    },
]


def seed() -> None:
    """Insert seed contractors into the database."""
    with Session(engine) as session:
        # Check if contractors already exist
        existing = session.execute(
            text("SELECT COUNT(*) FROM contractors")
        ).scalar()

        if existing and existing > 0:
            print(f"Database already has {existing} contractors. Skipping seed.")
            print("To re-seed, drop existing rows first: DELETE FROM contractors;")
            return

        contractors = [Contractor(**data) for data in CONTRACTORS]
        session.add_all(contractors)
        session.commit()

        print(f"Successfully seeded {len(contractors)} contractors.")
        print("  - 5 bathroom specialists")
        print("  - 5 kitchen specialists")
        print("  - 5 window specialists")
        print("  - 5 roofing specialists")
        print(f"  - Zip codes: 90210-90212, 10001-10003, 60601-60602")


if __name__ == "__main__":
    seed()
